server:
  address: 0.0.0.0
  port: 8000

spring:
  mvc:
    format:
      date: yyyy-MM-dd
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
logging:
  level:
    org.hibernate.type: trace